name: Changed files
description: Get all changed files
author: tj-actions
inputs:
  token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}
  separator:
    description: 'Split character for array output'
    required: true
    default: " "
  files:
    description: 'Check for file changes for all files listed (Defaults to the entire repo)'
    required: false
    default: ""

outputs:
  added_files:
    description: List of added files.
    value: ${{ steps.changed-files.outputs.added_files }}
  copied_files:
    description: List of copied files.
    value: ${{ steps.changed-files.outputs.copied_files }}
  deleted_files:
    description: List of deleted files.
    value: ${{ steps.changed-files.outputs.deleted_files }}
  modified_files:
    description: List of modified files.
    value: ${{ steps.changed-files.outputs.modified_files }}
  renamed_files:
    description: List of renamed files.
    value: ${{ steps.changed-files.outputs.renamed_files }}
  type_changed_files:
    description: List of files that had type changes.
    value: ${{ steps.changed-files.outputs.type_changed_files }}
  unmerged_files:
    description: List of unmerged files.
    value: ${{ steps.changed-files.outputs.unmerged_files }}
  unknown_files:
    description: List of unknown files.
    value: ${{ steps.changed-files.outputs.unknown_files }}
  all_changed_files:
    description: List of all changed files.
    value: ${{ steps.changed-files.outputs.all_changed_files }}
  all_modified_files:
    description: List of all copied modified and added files.
    value: ${{ steps.changed-files.outputs.all_modified_files }}
  any_changed:
    description: Return true only when any files provided using the files input have changed.
    value: ${{ steps.changed-files.outputs.any_changed }}

runs:
  using: 'composite'
  steps:
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: changed-files
      shell: bash
      env:
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_SEPARATOR: ${{ inputs.separator }}

branding:
  icon: file-text
  color: white
