name: Changed files
description: Get all changed files
author: tj-actions
inputs:
  token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}
  separator:
    description: 'Split character for array output'
    required: true
    default: " "
  files:
    description: 'Check for file changes for all files listed (Defaults to the entire repo)'
    required: false
    default: ""

outputs:
  added_files:
    description: List of added files.
  copied_files:
    description: List of copied files.
  deleted_files:
    description: List of deleted files.
  modified_files:
    description: List of modified files.
  renamed_files:
    description: List of renamed files.
  changed_files:
    description: List of changed files.
  unmerged_files:
    description: List of unmerged files.
  unknown_files:
    description: List of unknown files.
  all_changed_files:
    description: List of all changed files.
  all_modified_files:
    description: List of all copied modified and added files.
  any_changed:
    description: Return true only when any files provided using the files input have changed.

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: file-text
  color: white
