name: Multi Job Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: ./
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
  
  view-changed-files:
    name: View all changed files
    runs-on: ubuntu-latest
    needs: [changed-files]
    steps:
      - name: List all changed files
        run: |
          echo '${{ needs.changed-files.outputs.all_changed_files }}'
