name: CI

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show github context
        run: |
          echo "${{ toJSON(github.event) }}"
      - name: Run changed-files with defaults
        id: changed-files
        uses: ./

      - name: Show output
        run: |
          echo "${{ toJSON(steps.changed-files.outputs) }}"
      - name: Run changed-files with comma separator
        id: changed-files-comma
        uses: ./
        with:
          separator: ","
      - name: Show output
        run: |
          echo "${{ toJSON(steps.changed-files-comma.outputs) }}"
